# Generated by Django 5.1 on 2024-08-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0002_alter_customusuario_cartao_sus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='cartao_sus',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Cartão do SUS'),
        ),
    ]
