# Generated by Django 5.1 on 2024-08-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0004_alter_customusuario_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_exames',
            name='laudo',
            field=models.FileField(upload_to='media'),
        ),
    ]
