# Generated by Django 5.1 on 2024-08-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0005_alter_pedidos_exames_laudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_exames',
            name='dias_possíveis',
            field=models.CharField(max_length=20),
        ),
    ]
