# Generated by Django 5.1 on 2024-08-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0006_alter_pedidos_exames_dias_possíveis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos_exames',
            old_name='dias_possíveis',
            new_name='dias_possiveis',
        ),
        migrations.AlterField(
            model_name='status_exame',
            name='situacao',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado')], default='Pendente', max_length=20),
        ),
    ]
