# Generated by Django 5.1.1 on 2024-09-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0007_rename_dias_possíveis_pedidos_exames_dias_possiveis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='img/default.png', null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='pedidos_exames',
            name='data_modificacao',
            field=models.DateField(default='2024-09-12'),
        ),
        migrations.AddField(
            model_name='pedidos_exames',
            name='data_publicacao',
            field=models.DateField(default='2024-09-12', editable=False),
        ),
        migrations.AlterField(
            model_name='pedidos_exames',
            name='laudo',
            field=models.FileField(upload_to='uploads_laudo/'),
        ),
    ]
