# Generated by Django 5.0 on 2024-10-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionário', '0002_alter_customusuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
