# Generated by Django 5.0 on 2024-10-09 22:08

import Funcionário.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionário', '0003_alter_customusuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='foto_perfil',
            field=stdimage.models.StdImageField(blank=True, default='img/default.png', force_min_size=False, null=True, upload_to=Funcionário.models.get_file_path, variations={'thumb': {'crop': True, 'height': 30, 'width': 30}}),
        ),
        migrations.AlterField(
            model_name='notificacoes',
            name='conteudo',
            field=models.TextField(default='Pedido confirmado'),
        ),
    ]
