# Generated by Django 5.0 on 2024-10-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionário', '0004_alter_customusuario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_exames',
            name='dia_marcado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
