# Generated by Django 5.0 on 2024-10-10 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionário', '0005_alter_pedidos_exames_dia_marcado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_exames',
            name='situacao',
            field=models.ForeignKey(default='Pendente', on_delete=django.db.models.deletion.CASCADE, to='Funcionário.status_exame'),
        ),
    ]
