# Generated by Django 5.0 on 2024-10-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionário', '0007_alter_pedidos_exames_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_exames',
            name='dia_marcado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
