# Generated by Django 5.0 on 2024-10-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionário', '0008_alter_pedidos_exames_dia_marcado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_exame',
            name='situacao',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado'), ('Concluído', 'Concluído')], default='Pendente', max_length=20),
        ),
    ]
