# Generated by Django 5.0 on 2024-10-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionário', '0009_alter_status_exame_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacoes',
            name='criado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificacoes',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pedidos_exames',
            name='criado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedidos_exames',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tipo_exame',
            name='criado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tipo_exame',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
