# Generated by Django 5.0 on 2024-10-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionário', '0010_alter_notificacoes_criado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacoes',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Funcionário.pedidos_exames'),
        ),
    ]
