# Generated by Django 5.0 on 2024-10-16 03:17

import Funcionário.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionário', '0011_notificacoes_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='foto_perfil',
            field=stdimage.models.StdImageField(blank=True, default='img/default.png', force_min_size=False, null=True, upload_to=Funcionário.models.get_file_path, variations={'thumb': {'crop': True, 'height': 100, 'width': 100}}),
        ),
    ]
