# Generated by Django 5.0 on 2024-12-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionário', '0012_alter_customusuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_exame',
            name='situacao',
            field=models.CharField(default='Pendente', max_length=20),
        ),
    ]
