# Generated by Django 5.0 on 2024-12-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionário', '0013_alter_status_exame_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
