# Generated by Django 5.0 on 2024-12-11 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionário', '0014_alter_customusuario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacoes',
            name='pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Funcionário.pedidos_exames'),
        ),
    ]
